apiVersion: v1
kind: Secret
metadata:
        name: my-secret
        annotations:
                kubernetes.io/service-account.name: "myserviceaccount"
type: kubernetes.io/service-account-token
data:
        # You can include additional key value pairs as you do with Opaque Secrets
